#+OPTIONS: ^:nil

* Tasks
** TODO Add next_paydate() function to invoice
   Returns dt for next payday, has to know some previous payday to
   calculate every second week, or maybe just `if now::week_num % 2`
   because we started invoicing at the end of week 1 in the new year.
** TODO The use of invoice.send() doesen't really matter
   A few tests called send(), but commenting those calls out didn't
   affect the outcome of the test.  I was thinking each entry could
   just record some maybe interesting information about its parent
   invoice, while really trying to defer on making an entry point back
   to its invoice, something like Entry --> Invoice.  Right now its
   only Invoice --> [Entry, Entry, ...].  I was also thinking that an
   invoice's ID could be computed from the interesting information,
   but why not just use a real parent-child relation with formal ids?
   And this all seems premature anyways.  Maybe I don't care enough
   about send() to justify its existence, yet.

   I found a use for it, it sets the invoiced_datetime property on the
   invoice, which is used by print_txt().

   But I'm still not sure how I even "send" an invoice, beyond the
   mechanical steps of:
   1. sync phone
   2. copy hour entries from Notes app into notes.txt
   3. run gen_invoice_task, I can specify a variabe in the file to
      select which company to invoice for
   4. copy-paste line-items from invoice txt file to another Notes app
      note
   5. sync phone
   6. text Ken
** TODO Re-evaluate tests for payment_date in Invoice
   Just changed all net_30 date-times to None, and no tests broke.
   Make tests break, then fix the code.
** TODO Move all IO stuff out of TimeEntry, Invoice, and CompanyJobs
   Methods or classmethods, like =Invoice.write_file()=,
   =TimeEntry.parse_note()=, or =CompanyJobs.get_jobs_from_ini()=,
   belong in a separate IO layer.  Maybe something like io/txt_files.
** TODO Make it so: ~invoice == read_invoice(write_invoice(invoice)))~
